[package]
name          = "rosu-v2"
version       = "0.3.1"
authors       = ["MaxOhn <ohn.m@hotmail.de>"]
edition       = "2018"
description   = "An osu! API v2 wrapper"
license       = "MIT"
readme        = "README.md"
keywords      = ["osu", "api", "wrapper"]
repository    = "https://github.com/MaxOhn/rosu-v2"
documentation = "https://docs.rs/rosu-v2/"

# --- Features ---

[features]
default = ["cache"]
cache = ["dashmap"]
metrics = ["prometheus"]

# --- Dependencies ---

[dependencies]
bitflags = { version = "1.0", default-features = false }
bytes = { version = "1.0", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
futures = { version = "0.3", default-features = false }
log = { version = "0.4", default-features = false }
hyper = { version = "0.14", default-features = false, features = ["client"] }
hyper-rustls = { version = "0.23", default-features = false, features = ["http1", "http2", "native-tokio"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
smallstr = { version = "0.2", features = ["serde"] }
tokio = { version = "1.0", default-features = false, features = ["macros"] }
url = { version = "2.0", default-features = false }

# --- Feature dependencies ---

dashmap = { version = "4.0", default-features = false, optional = true }
prometheus = { version = "0.13", optional = true }
rkyv = { version = "0.7", optional = true }

# --- Dev dependencies ---

[dev-dependencies]
dotenv = { version = "0.15" }
env_logger = { version = "0.9" }
once_cell = { version = "1.7" }
tokio = { version = "1.0", default-features = false, features = ["rt", "macros"] }
