[package]
name          = "rosu-v2"
version       = "0.1.0"
authors       = ["MaxOhn <ohn.m@hotmail.de>"]
edition       = "2018"
description   = "An osu! API v2 wrapper"
license       = "MIT"
readme        = "README.md"
keywords      = ["osu", "api", "wrapper"]
repository    = "https://github.com/MaxOhn/rosu-v2"
documentation = "https://docs.rs/rosu-v2/"

[dependencies.bitflags]
version = "1.2"

[dependencies.bytes]
version = "1.0"
default-features = false

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["serde"]

[dependencies.log]
version = "0.4"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "multipart"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.tokio]
version = "1.2"
default-features = false
features = ["rt", "macros"]

[dev-dependencies.dotenv]
version = "0.15"

[dev-dependencies.env_logger]
version = "0.8"

[dev-dependencies.once_cell]
version = "1.7"
